### ISSUE TITLE
no other way to contact you

### ISSUE THREAD

**Issue by RandomLegend** [TeaWithLucas/fmg-mapview#1]
Hello,

since i have no other way to contact you i opened this issue, im sorry for the inconvenience.

May i ask if you 1. still have to code for the herosaver.js repo that got shut down and 2. maybe send it to me? I still got a working one wich i can execute, but it wont get all the model details and is exporting too small (it was forked in Oct. 2019)

Thank you for your time

**Comment by TeaWithLucas** [comment]
@Smart-Helper I cant find a local copy atm, ask @lillypath869, they might have a copy while i look

**Comment by hero-saver** [comment]
@Smart-Helper, There is a copy here: https://github.com/hero-saver/threejs

**Comment by RandomLegend** [comment]
Oh perfect guys!

Are there any plans on keeping the code up to date to accomodate for changes HeroForge could apply in near future? And were could one follow these updates?

**Comment by RandomLegend** [comment]
closed
